name: Acciojob score evaluation
on: push
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name}} event."
      - run: echo " This job is now running on a s{{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github. repository }}."
      - name: Check out repository code 
        uses: actions/checkout@v2
      - name: Get node v16
        uses: actions/setup-node@v3 
        with:
          node-version: 16
      - run: echo " The workflow is now ready to test your code on the runner."
      - run: echo " The ${{ github. repository }} repository has been cloned to the runner."
      - name: List files in the repository 
        run:
          ls ${{ github.workspace }}
      - name: Acciojob Assignment Action 
        id: assignmentAction 
        uses: accioiob/assignment-action@v0.o.2 
        env:
         ACCIO_ASGMNT_ACTION_TOKEN: ${{ secrets.ACCIO_ASGMNT_ACTION_TOKEN }}
      - run: echo "Score - ${{ steps.assignmentAction.outputs.scoreReceived }}/${{ steps.assignmentAction.outputs.totalScore }}"
